# Generated by Django 3.0.7 on 2020-08-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200804_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_votes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
