# Generated by Django 3.0.7 on 2020-08-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200804_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='num_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
