# Generated by Django 3.0.5 on 2020-06-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(default='Anonymous', max_length=60),
            preserve_default=False,
        ),
    ]
