# Generated by Django 3.0.7 on 2020-07-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200715_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Sponsor'), (1, 'Author')], default=1),
        ),
    ]
