# Generated by Django 3.0.5 on 2020-06-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200601_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Voter'), (1, 'Author')], default=0),
        ),
    ]
