# Generated by Django 3.0.7 on 2020-06-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='anon', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
