# Generated by Django 3.0.7 on 2020-06-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
