# Generated by Django 3.0.7 on 2020-07-21 03:04

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200626_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
