# Generated by Django 3.0.7 on 2020-08-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20200812_0339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstoryvotes',
            unique_together=set(),
        ),
    ]
