# Generated by Django 3.0.5 on 2020-06-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200208_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coupon_code', models.CharField(default=None, max_length=10)),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('requires_subscription', models.BooleanField(default=True)),
            ],
        ),
    ]
