# Generated by Django 3.0.5 on 2020-06-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='coupon_amount',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='coupon_code',
        ),
        migrations.AlterField(
            model_name='plan',
            name='requires_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
